context.modules = [
  {
    name = libpipewire-module-filter-chain
    args = {
      node.description = "Noise Suppressed Blue Yeti Mic"
      media.name       = "Noise Suppressed Blue Yeti Mic"
      filter.graph = {
        nodes = [
          # Noise suppression filter
          {
            type    = ladspa
            name    = deepfilter
            plugin  = /usr/lib/ladspa/libdeep_filter_ladspa.so
            label   = deep_filter_mono
            control = {
              "Attenuation Limit (dB)" = 100
            }
          }

          # Noise gate to keep mic from showing up as always active from inaudible input
          # that makes it through deepfilter
          {
            type    = ladspa
            name    = noise_gate
            plugin  = /usr/lib/ladspa/gate_1410.so
            label   = gate
            control = {
              "LF key filter (Hz)"  = 100.0
              "HF key filter (Hz)"  = 8000.0

              # Mic still shows activity in silence - raise threshold (e.g. -45, -40)
              # Lower threshold if cutting of start of words
              "Threshold (dB)"      = -50.0

              "Attack (ms)"         = 10.0

              # Gate closes too fast between words: increase hold and/or decay
              "Hold (ms)"           = 150.0
              "Decay (ms)"          = 200.0
              "Range (dB)"          = -90.0   # how silent the gate gets when closed
              "Output select (-1 = key listen, 0 = gate, 1 = bypass)" = 0
            }
          }
        ]

        links = [
          # deepfilter uses "Audio In" and "Audio Out"
          # noise_gate uses "Input" and "Output"
          # Use analyseplugin on the filter's .so to find the input and output channel names
          { output = "deepfilter:Audio Out" input = "noise_gate:Input" }
        ]
      }

      capture.props = {
        node.name        = "capture.rnnoise_source"
        node.passive     = true        # critical: won't hold Yeti awake alone
        target.object    = "blue_yeti_mic_input"
        audio.rate       = 48000
        audio.channels   = 1
        audio.position   = [ MONO ]
      }

      playback.props = {
        node.name        = "rnnoise_source"
        media.class      = "Audio/Source"
        node.description = "Noise Suppressed Blue Yeti Mic"
        audio.rate       = 48000
        audio.channels   = 1
        audio.position   = [ MONO ]
      }
    }
  }
]
